```{r}
library(ggplot2)
library(data.table)

```

```{r}
df <- fread('Economist_Assignment_Data.csv', drop=1)

head(df)
```


```{r}
ggplot(df, aes(x=CPI, y=HDI, colour=factor(Region))) +
  geom_point() +
  labs(color='Region')
```

```{r}
ggplot(df, aes(x=CPI, y=HDI, colour=factor(Region))) +
  geom_point(shape=1, size=4) +
  labs(color='Region')
```


```{r}
ggplot(df, aes(x=CPI, y=HDI, colour=factor(Region))) +
  geom_point(shape=1, size=4) +
  labs(color='Region') +
  geom_smooth(aes(group=1))
```


```{r}
ggplot(df, aes(x=CPI, y=HDI, colour=factor(Region))) +
  geom_point(shape=1, size=4) +
  labs(color='Region') +
  geom_smooth(aes(group=1), method='lm', formula = y ~ log(x), se = FALSE, color = 'red')
```


```{r}
ggplot(df, aes(x=CPI, y=HDI, colour=factor(Region))) +
  geom_point(shape=1, size=4) +
  labs(color='Region') +
  geom_smooth(aes(group=1), method='lm', formula = y ~ log(x), se = FALSE, color = 'red') + 
  geom_text(aes(label=Country))
```


```{r}
pointsToLabel <- c("Russia", "Venezuela", "Iraq", "Myanmar", "Sudan",
                   "Afghanistan", "Congo", "Greece", "Argentina", "Brazil",
                   "India", "Italy", "China", "South Africa", "Spane",
                   "Botswana", "Cape Verde", "Bhutan", "Rwanda", "France",
                   "United States", "Germany", "Britain", "Barbados", "Norway", "Japan",
                   "New Zealand", "Singapore")
ggplot(df, aes(x=CPI, y=HDI, colour=factor(Region))) +
  geom_point(shape=1, size=4) +
  labs(color='Region') +
  geom_smooth(aes(group=1), method='lm', formula = y ~ log(x), se = FALSE, color = 'red') + 
  geom_text(aes(label = Country), color = "gray20", 
                data = subset(df, Country %in% pointsToLabel),check_overlap = TRUE)
```


```{r}
ggplot(df, aes(x=CPI, y=HDI, colour=factor(Region))) +
  geom_point(shape=1, size=4) +
  labs(color='Region') +
  geom_smooth(aes(group=1), method='lm', formula = y ~ log(x), se = FALSE, color = 'red') + 
  geom_text(aes(label = Country), color = "gray20", 
                data = subset(df, Country %in% pointsToLabel),check_overlap = TRUE) +
  theme_bw()
```


```{r}
ggplot(df, aes(x=CPI, y=HDI, colour=factor(Region))) +
  geom_point(shape=1, size=4) +
  labs(color='Region') +
  geom_smooth(aes(group=1), method='lm', formula = y ~ log(x), se = FALSE, color = 'red') + 
  geom_text(aes(label = Country), color = "gray20", 
                data = subset(df, Country %in% pointsToLabel),check_overlap = TRUE) +
  theme_bw() +
  scale_x_continuous(name='Corruption Perceptions Index, 2011 (10=least corrupt)', limits=c(1,10), breaks=1:10)
```


```{r}
ggplot(df, aes(x=CPI, y=HDI, colour=factor(Region))) +
  geom_point(shape=1, size=4) +
  labs(color='Region') +
  geom_smooth(aes(group=1), method='lm', formula = y ~ log(x), se = FALSE, color = 'red') + 
  geom_text(aes(label = Country), color = "gray20", 
                data = subset(df, Country %in% pointsToLabel),check_overlap = TRUE) +
  theme_bw() +
  scale_x_continuous(name='Corruption Perceptions Index, 2011 (10=least corrupt)', limits=c(1,10), breaks=1:10) +
  scale_y_continuous(name='Human Development Index, 2011 (1=Best)', limits=c(0.2,1), breaks=c(0.2,0.4,0.6,0.8,1))
```

```{r}
ggplot(df, aes(x=CPI, y=HDI, colour=factor(Region))) +
  geom_point(shape=1, size=4) +
  labs(color='Region') +
  geom_smooth(aes(group=1), method='lm', formula = y ~ log(x), se = FALSE, color = 'red') + 
  geom_text(aes(label = Country), color = "gray20", 
                data = subset(df, Country %in% pointsToLabel),check_overlap = TRUE) +
  theme_bw() +
  scale_x_continuous(name='Corruption Perceptions Index, 2011 (10=least corrupt)', limits=c(1,10), breaks=1:10) +
  scale_y_continuous(name='Human Development Index, 2011 (1=Best)', limits=c(0.2,1), breaks=c(0.2,0.4,0.6,0.8,1)) +
  ggtitle(label = 'Corruption and Human Development')
```


```{r}
library(plotly)
dvp <- ggplot(df, aes(x=CPI, y=HDI, colour=factor(Region))) +
  geom_point(shape=1, size=4) +
  labs(color='Region') +
  geom_smooth(aes(group=1), method='lm', formula = y ~ log(x), se = FALSE, color = 'red') + 
  geom_text(aes(label = Country), color = "gray20", 
                data = subset(df, Country %in% pointsToLabel),check_overlap = TRUE) +
  theme_bw() +
  scale_x_continuous(name='Corruption Perceptions Index, 2011 (10=least corrupt)', limits=c(1,10), breaks=1:10) +
  scale_y_continuous(name='Human Development Index, 2011 (1=Best)', limits=c(0.2,1), breaks=c(0.2,0.4,0.6,0.8,1)) +
  ggtitle(label = 'Corruption and Human Development')

ggplotly(dvp)

```













